OpsSystem/asset/urls.py
from django.conf.urls import url
from views import *


urlpatterns=[url('^asset/overview$',overview,name='overview'),
	url('^asset/query_cmd_log$',query_cmd_log,name='query_cmd_log'),
	url('^asset/list_cmd_opt_log$',list_cmd_opt_log,name='list_cmd_opt_log'),
	]

OpsSystem/deploy/urls.py
from django.conf.urls import url
from views import * 
urlpatterns=[
	url(r'^add_svn_repo/$',add_svn_repo,name='add_svn_repo'),
	url(r'^add_git_repo/$',add_git_repo,name='add_git_repo'),
	url(r'^list_repo_info/$',list_repo_info,name='list_repo_info'),
	url(r'^list_deploy_info/$',list_deploy_info,name='list_deploy_info'),
	url(r'^deploy_project/$',deploy_project,name='deploy_project')
	]

OpsSystem/ops_system/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from ops_system.views import index
from ops_system.views import login_view,logout_view
urlpatterns = [
    url(r'^$',login_view,name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^index/$',index,name='index'),
    url(r'^asset/', include('asset.urls',namespace='asset',app_name='asset')),
    url(r'^deploy-manage/',include('deploy.urls',namespace='deploy-manage',app_name='deploy')),
    url(r'^saltstack/',include('salts.urls',namespace='saltstack',app_name='salts')),
    url(r'^logout/$',logout_view,name='logout'),
	]

OpsSystem/salts/urls.py
from django.conf.urls import url
from views import *


urlpatterns=[
	url('^hosts/host_info$',list_host_info,name='host_info'),
	url('^hosts/deploy/application$',deploy_application,name='deploy'),
	url('^hosts/refresh_host_info$',refresh_host_info,name='refresh_host_info'),
	url('^hosts/list_app_deploy_info$',list_app_deploy_info,name='list_app_deploy_info'),
	url('^hosts/list_cmd_run_info$',list_cmd_run_info,name='list_cmd_run_info'),
	url('^hosts/cmd_run$',cmd_run,name='cmd_run'),
	url('^hosts/download_file$',download_file,name='download_file'),
	]

OpsSystem/templates/add_git_repo.html
{%extends 'base.html' %}
{%load static %}
{%block head%}
<li>
   <i class='fa fa-dashboard'></i><a href={%url 'index' %}>&nbsp Dashboard</a>
</li>
<li>
   <i class='fa fa-table'></i>&nbsp 项目管理
</li>
<li >
<i class='fa fa-building-o'></i>&nbsp; 添加版本库
</li>
<li class='active'>
<i ></i> Git 
</li>
{%endblock%}

{%block page_content%}

<div class='row'>
    <div class='panel panel-info'>
     <div class='panel-heading'>
	 <h3 class='panel-title'><i class='fa fa-bell'></i>&nbsp 添加Git库信息<h3>
     </div>
     <div class='panel-body'>
          <div class='panel panel-info' style='width:700px;height:1300px;margin:auto'>
	      <div class='panel-body'>
		  <form class='form-group' action={%url 'deploy:add_git_repo'%} method='post'>
		      {% csrf_token %}
		      {%for f in form %}
		      <div class='form-group input-group' style='width:650px;'>
			  <label class='input-group-addon control-label' style='width:150px'> {{f.label}}</label> 
			  {{f}}
		      </div>
		         {%if f.errors %}
			  <div class='alert alert-danger'> {{f.errors}}</div>
			  {%endif%}
		      {%endfor%}
		      <p> 
		      <div class='form-group input-group'>
		      </div>
		      <div class='form-group input-group'>
		      </div>
		      <button type='reset' class='btn  btn-danger' value='reset' style='margin-left:100px;width:100px'>Reset</button>
		      <button type='submit' class='btn  btn-primary' value='submit' style='margin-left:200px;width:100px'>Submit</button>
		      </p>
		      </form>
	      </div>
	  </div>
	 <div>

    </div>
</div>


{%endblock%}

OpsSystem/templates/deploy_project.html
{%extends 'base.html' %}
{%load static %}
{%block head%}
<li>
<i class='fa fa-dashboard'></i><a href={%url 'index' %}>&nbsp Dashboard</a>
</li>
<li>
<i class='fa fa-table'></i>&nbsp 项目管理
</li>
<li  class='active'>
<i class='fa fa-building-o'></i>&nbsp; 发布工程
</li>
{%endblock%}

{%block page_content%}

<div class='row'>
    <div class='panel panel-info'>
	<div class='panel-heading'>
	    <h4 class='panel-title'><i class='fa fa-bell'></i>&nbsp Deploy Project<h4>
		</div>
		<div class='panel-body'>
		    <div class='panel panel-info' style='width:400px;height:600px;margin:auto'>
			<form class='form-group' method='post' action={%url 'deploy:deploy_project'%} onsubmit='return validation();'>
			    {%csrf_token %}
			    {%for f in form %}
			    <div class='form-group input-group'>
				<label class='input-group-addon control-label'>{{f.label}}</label>  {{f}}
			    </div>
			    {%if f.errors%}
			    {%if res %}
			    <div class='alert alert-success'>
				{{f.errors}}
			    </div>
			    <div class='form-group input-group'>
			    </div>
			    {%else%}
			    <div class='alert alert-danger'>
				{{f.errors}}
			    </div>
			    <div class='form-group input-group'>
			    </div>
			    {%endif%}
			    {%endif%}
			    <div class='form-group input-group'>
			    </div>
			    <div class='form-group input-group'>
			    </div>
			    <div class='form-group input-group'>
			    </div>
			    <div class='form-group input-group'>
			    </div>
			    {%endfor%}
			    <div class='form-group input-group'>
			    </div>
			    <button style='width:300px;margin-left:50px' type='submit' value='deploy' id='sb' class='btn btn-danger'> Deploy </button>
			    <span id="sp_1" style="display:none;width:30px;margin-left:50px"><img style='width:100px;height:60px;'src={%static 'img/wait.gif'%}
				id="sp"/> 正在处理中.......</span> 
			</form>
			<script type="text/javascript"> 
			    function getId(id) { 
				return document.getElementById(id); 
			    } 
function validation() { 
    target=document.getElementById('id_password')
    if (target.value==null || target.value.replace(/(^\s*)|(\s*$)/g, "")=='')
    {
	alert('请输入发布密码!!!');
	return false;
    }

    getId("sb").style.display="none"; 
    getId("sp_1").style.display=""; 
    return true; 
} 
</script>
</div>
</div>
</div>
</div>

{%if log %}
<div class='row'>
    <div class='panel'> 
	<div class='panel-body'>
	    <div class='panel panel-info' style='width:700px;height:1200px;margin:auto;'>
		<div class='alert alert-info'>
		    <textarea style='width:100%;height:1000px;background: #300a24'>
			发布日志
			{{log}}
		    </textarea>
		    </div>
		</div>
	    </div>
	</div>
    </div>
    {%endif%}
    {%endblock%}

OpsSystem/templates/download_file.html
{%extends 'base.html' %}
{%load static %}
{%block head%}
<li>
<i class='fa fa-dashboard'></i><a href={%url 'index' %}>&nbsp Dashboard</a>
</li>
<li>
<i class='fa fa-table'></i>&nbsp SaltStack
</li>
<li  class='active'>
<i class='fa fa-building-o'></i>&nbsp;文件下载
</li>
{%endblock%}

{%block page_content%}

<div class='row'>
    <div class='panel panel-info'>
	<div class='panel-heading'>
	    <h3 class='panel-title'><i class='fa fa-bell'></i>&nbsp Download File<h3>
		</div>
		<div class='panel-body'>
		    <div class='panel panel-info' style='width:900px;height:600px;margin:auto'>
                     <div class='row' >
			 <div class="col-lg-9" > 
			     <form class='form-group' method='post' action={%url 'salts:download_file'%} onsubmit='return validation();'>
				 {%csrf_token%}
				 <div class='form-group input-group'>
				 </div>
                                <div class='form-group input-group' style='margin-left:20px;margin-top:20px' >
				 <span class='input-group-btn'>
				     <button class='btn btn-default' type='button' style='width:100px'>
					 目标主机
				     </button>
				 </span>
			             {{form.target}}
			         </div>
                             {% if form.target.errors %}
			     <div class='form-group input-group' style='width:100%'>
				 <div class='alert alert-danger' style='text-align:center'> {{form.target.errors}} </div>
			     </div>
			     {%endif%}
                                <div class='form-group input-group' style='margin-top:200px;margin-left:20px' >
				 <span class='input-group-btn'>
				     <button class='btn btn-default' type='button' style='width:100px'>
				         文件路径	
				     </button>
				 </span>
			             {{form.file_path}}
			         </div>
                            {% if form.file_path.errors %}
			     <div class='form-group input-group' style='width:100%'>
				 <div class='alert alert-danger' style='text-align:center'> {{form.file_path.errors}} </div>
			     </div>
			     {%endif%}
                           

                  <div class='input-group' style='margin:auto;width:400px'>
			     <button class='btn btn-success' type='submit' value='deploy' id='d' style='width:400px;margin-top:100px'> Download </button>
		<span id='r' style='display:none;width:200px;margin-top:500px'><img style='width:200px;height:200px;' src={%static 'img/wait.gif'%} />正在下载.......</span>
			     </div>
                             <script type='text/javascript'>
				 function validation(){
				    var target=document.getElementById('id_target');
				    var path=document.getElementById('id_file_path')
				    if (target.value==null || target.value.replace(/(^\s*)|(\s*$)/g, "")=='')
				    {
				            alert('请输入目标主机!!!');
					    return false;
				    }
				    if(path.value==null||path.value.replace(/(^\s*)|(\s*$)/g, "")==''){
				            alert('请输入文件绝对路径！！！')
				            return false;
				    }
				    return true;
				 }
			     </script>
			      </form>

			       {{file}}
			 </div>
		     </div>
		    </div>
	  	</div>
	    </div>
	</div>
{%if result %}
<div class='row'>
<div class='panel'> 
<div class='panel-body'>
<div class='panel panel-info' style='width:900px;height:1200px;margin:auto;'>
<div class='alert alert-info'>
<textarea style='width:100%;height:1000px;background: #300a24'>
命令执行结果：
{{result}}
</textarea>
</div>
</div>
</div>
</div>
</div>
{%endif%}
	{%endblock%}

OpsSystem/templates/host_list.html
{%extends 'base.html' %}
{%load static %}
{%block head%}
<li>
<i class='fa fa-dashboard'> </i><a href={%url 'index' %}> Dashboard </a>
</li>
<li class='active'>
  <i class='fa fa-table'></i>主机列表
</li>
{%endblock %}

OpsSystem/templates/list_app_deploy_info.html
{%extends 'base.html' %}
{%load static %}
{%block head%}
<li>
   <i class='fa fa-dashboard'></i><a href={%url 'index' %}>&nbsp Dashboard</a>
</li>
<li>
   <i class='fa fa-table'></i>&nbsp SaltStack
</li>
<li  class='active'>
<i class='fa fa-building-o'></i>&nbsp; 部署记录
</li>
{%endblock%}

{%block page_content%}

<div class='row'>
    <div class='panel panel-info'>
     <div class='panel-heading'>
	 <h3 class='panel-title'><i class='fa fa-bell'></i>&nbsp 部署记录<h3>
     </div>
     <div class='panel-body'>
          <div class='panel panel-info' style='width:auto;height:600px;margin:auto'>
	      <div class='table-responsive'>
		  <table class="table table-striped table-bordered">
		      <thead>
			  <tr class='info'>
			      <th>操作用户</th>
			      <th>部署时间</th>
			      <th>匹配目标</th>
			      <th>部署应用</th>
			      <th>部署成功主机</th>
			      <th>部署失败主机</th>
			      <th>影响主机数</th>
			      <th>总耗时</th>
			  </tr>
		      </thead>
		      <tbody>
		      {%for info in app_info %}
		      <tr>
		      <td>{{info.user}}</td>
		      <td>{{info.time}}</td>
		      <td>{{info.target}}</td>
		      <td>{{info.application}}</td>
		      <td>{{info.success_hosts}}</td>
		      <td>{{info.failed_hosts}}</td>
		      <td>{{info.total}}</td>
		      <td>{{info.duration}}</td>
                       </tr>
	            {%endfor%}
		      </tbody>
		  </table>
	  </div>
      </div>
	 </div>
  <div class='pager' style='argin-top:30px;width:auto;margin-left:50px'>
	  <span class='step-links'>
	      {%if app_info.has_previous %}
	      <li>  <a href="?page={{app_info.previous_page_number}}">&larr;Previous</a></li>
	      {%endif%}
	      <span class='current'>Page {{app_info.number}} of {{app_info.paginator.num_pages}}</span>
	      {%if app_info.has_next%}
	      <li> <a href="?page={{app_info.next_page_number}}">Next &rarr;</a></li>
	      {%endif%}
	  </span>
      </div>
	 
    </div>
</div>
{%endblock%}

OpsSystem/templates/query_host_cmd_log.html
{%extends 'base.html' %}
{%load static %}
{%block head%}
<li>
<i class='fa fa-dashboard'></i><a href={%url 'index' %}>&nbsp Dashboard</a>
</li>
<li>
<i class='fa fa-table'></i>&nbsp 资产管理
</li>
<li  class='active'>
<i class='fa fa-building-o'></i>&nbsp; 命令审计
</li>
{%endblock%}

{%block page_content%}

<div class='row'>
    <div class='panel panel-info'>
	<div class='panel-heading'>
	    <h4 class='panel-title'><i class='fa fa-bell'></i>&nbsp 命令审计<h4>
		</div>
		<div class='panel-body'>
		    <div class='panel panel-info' style='width:700px;height:600px;margin:auto'>
			<form class='form-group' method='post' action={%url 'asset:query_cmd_log'%} onsubmit='return validation();'>
			    {%csrf_token %}
			    {%for f in form %}
			    {%if f.label = "Begin" or f.label = "End" %}
			    <div class='form-group input-group date' id='{{f.label}}' style='margin-top:90px;margin-left:40px'>
				<span class='input-group-btn'>
				    <button class='btn btn-default' type='button' style='width:100px'>
					{%if f.label = "Begin" %}
					开始时间
					{%else%}
					结束时间
					{%endif%}
				    </button>
				</span>
				{{f}}
				<span class="input-group input-group-addon" style='float:left;height:34px;width:34px' >
				    <span class="input-group glyphicon glyphicon-calendar"></span>
				</span>
			    </div>
			    {%else%}
			    <div class='form-group input-group' style='margin-left:40px;margin-top:20px' >
				<span class='input-group-btn'>
				    <button class='btn btn-default' type='button' style='width:100px'>
					目标主机
				    </button>
				</span>
				{{f}}
			    </div>
			    {%endif%}
			    {%endfor%}
			    <div class='input-group' style='margin-left:150px;width:200px'>
				<button class='btn btn-outline btn-success' type='submit' value='deploy' id='d' style='width:200px;margin-top:100px'> Query </button>
			    </div>
			</form>

			<script type="text/javascript">
			    $(function () {
				    $('#Begin').datetimepicker({format: 'yyyy-mm-dd hh:ii:ss',language: 'zh-CN'});
				    });
</script>
<script type="text/javascript">
    $(function () {
	    $('#End').datetimepicker({format: 'yyyy-mm-dd hh:ii:ss',language: 'zh-CN'});
	    });
</script>

				    </div>
				</div>
			    </div>
			</div>
			{%endblock%}

OpsSystem/templates/salt_cmd_run.html
{%extends 'base.html' %}
{%load static %}
{%block head%}
<li>
<i class='fa fa-dashboard'></i><a href={%url 'index' %}>&nbsp Dashboard</a>
</li>
<li>
<i class='fa fa-table'></i>&nbsp SaltStack
</li>
<li  class='active'>
<i class='fa fa-building-o'></i>&nbsp;命令执行 
</li>
{%endblock%}

{%block page_content%}

<div class='row'>
    <div class='panel panel-info'>
	<div class='panel-heading'>
	    <h3 class='panel-title'><i class='fa fa-bell'></i>&nbsp 命令执行<h3>
		</div>
		<div class='panel-body'>
		    <div class='panel panel-info' style='width:900px;height:600px;margin:auto'>
                     <div class='row' >
			 <div class="col-lg-9" > 
			     <form class='form-group' method='post' action={%url 'salts:cmd_run'%} onsubmit='return validation();'>
				 {%csrf_token%}
				 <div class='form-group input-group'>
				 </div>
                                <div class='form-group input-group' style='margin-left:20px;margin-top:20px' >
				 <span class='input-group-btn'>
				     <button class='btn btn-default' type='button' style='width:100px'>
					 目标主机
				     </button>
				 </span>
			             {{form.target}}
			         </div>
                             {% if error %}
			     <div class='form-group input-group' style='width:100%'>
				 <div class='alert alert-danger' style='text-align:center'> {{error}} </div>
			     </div>
			     {%endif%}


				 <div class='form-group input-group' style='margin-top:60px;float:left'>
                                  <label class='checkbox-inline' style='margin-left:0px'>
				     <button class='btn btn-default' type='button' style='width:100px;'> 匹配模式 </button>
				 </label>
				 {%for f in form.mapping %}
				       <label class='checkbox-inline'>
					    {{f.tag}}
					    {{f.choice_label}}
				       </label> 
				 {%endfor%}
				  </div> 
                                <div class='form-group input-group' style='margin-top:200px;margin-left:20px' >
				 <span class='input-group-btn'>
				     <button class='btn btn-default' type='button' style='width:100px'>
				         Command	
				     </button>
				 </span>
			             {{form.cmdline}}
			         </div>
                            {% if form.cmdline.errors %}
			     <div class='form-group input-group' style='width:100%'>
				 <div class='alert alert-danger' style='text-align:center'> {{form.cmdline.errors}} </div>
			     </div>
			     {%endif%}
                            {% if cmd_error %}
			     <div class='form-group input-group' style='width:100%'>
				 <div class='alert alert-danger' style='text-align:center'> {{cmd_error}} </div>
			     </div>
			     {%endif%}


                  <div class='input-group' style='margin:auto;width:400px'>
			     <button class='btn btn-danger' type='submit' value='deploy' id='d' style='width:400px;margin-top:100px'> Run </button>
		<span id='r' style='display:none;width:200px;margin-top:500px'><img style='width:200px;height:200px;' src={%static 'img/wait.gif'%} />正在运行.......</span>
			     </div>
                             <script type='text/javascript'>
				 function validation(){
				    var target=document.getElementById('id_target');
				    var cmd=document.getElementById('id_cmdline')
				    if (target.value==null || target.value.replace(/(^\s*)|(\s*$)/g, "")=='')
				    {
				            alert('请输入目标主机!!!');
					    return false;
				    }
				    if(cmd.value==null||cmd.value.replace(/(^\s*)|(\s*$)/g, "")==''){
				            alert('请输入命令！！！')
				            return false;
				    }
				    document.getElementById('d').style.display="none";
				    document.getElementById('r').style.display='';
				    return true;
				 }
			     </script>
			      </form>

			 </div>
		     </div>
		    </div>
	  	</div>
	    </div>
	</div>
{%if result %}
<div class='row'>
<div class='panel'> 
<div class='panel-body'>
<div class='panel panel-info' style='width:900px;height:1200px;margin:auto;'>
<div class='alert alert-info'>
<textarea style='width:100%;height:1000px;background: #300a24'>
命令执行结果：
{{result}}
</textarea>
</div>
</div>
</div>
</div>
</div>
{%endif%}
	{%endblock%}

OpsSystem/templates/salt_deploy_application.html
{%extends 'base.html' %}
{%load static %}
{%block head%}
<li>
<i class='fa fa-dashboard'></i><a href={%url 'index' %}>&nbsp Dashboard</a>
</li>
<li>
<i class='fa fa-table'></i>&nbsp SaltStack
</li>
<li  class='active'>
<i class='fa fa-building-o'></i>&nbsp; 应用部署
</li>
{%endblock%}

{%block page_content%}

<div class='row'>
    <div class='panel panel-info'>
	<div class='panel-heading'>
	    <h3 class='panel-title'><i class='fa fa-bell'></i>&nbsp 应用部署<h3>
		</div>
		<div class='panel-body'>
		    <div class='panel panel-info' style='width:800px;height:600px;margin:auto'>
                     <div class='row' >
			 <div class="col-lg-10" > 
			     <form class='form-group' method='post' action={%url 'salts:deploy'%} onsubmit='return validation();'>
				 {%csrf_token%}
			     <div class='form-group input-group' style='margin-left:20px;margin-top:20px' >
				 <span class='input-group-btn'>
				     <button class='btn btn-default' type='button' style='width:100px'>
					 目标主机
				     </button>
				 </span>
				 <input type='text' class='form-control' id='target' name='target'>
			     </div>
			     {% if error %}
			     <div class='form-group input-group' style='width:100%'>
				 <div class='alert alert-danger' style='text-align:center'> {{error}} </div>
			     </div>
			     {%endif%}
			     <div class='form-group input-group' style='margin-top:60px;float:left'>
				 <label class='checkbox-inline' style='margin-left:0px'>
				     <button class='btn btn-default' type='button' style='width:100px;'> 匹配模式 </button>
				 </label>
				 <label class='checkbox-inline'>
				     <input type='radio' name='map' id='r1' value='list'>List
				 </label>
				 <label class='checkbox-inline'>
				     <input type='radio' name='map' id='r2' value='grain'>Grain
				 </label>
				 <label class='checkbox-inline'>
				     <input type='radio' name='map' id='r3' value='pcre'>Regrex
				 </label>
				 <label class='checkbox-inline'>
				     <input type='radio' name='map' id='r4' value='glob' checked>Hostname
				 </label>
				 <label class='checkbox-inline'>
				     <input type='radio' name='map' id='r5' value='nodegroup'>Nodegroup
				 </label>
			     </div>
                             <div class='form-group input-group' style='margin-top:60px;float:left'>
				 <label class='checkbox-inline' style='margin-left:0px'>
				     <button class='btn btn-default' type='button' style='width:100px;'> 部署应用 </button>
				 </label>
				 <label class='checkbox-inline'>
				     <input type='radio' name='app' id='r1' value='zabbix' checked>Zabbix Agent
				 </label>
				 <label class='checkbox-inline'>
				     <input type='radio' name='app' id='r2' value='mysql'>Mysql
				 </label>
				 <label class='checkbox-inline'>
				     <input type='radio' name='app' id='r3' value='nginx'>Nginx
				 </label>
				 <label class='checkbox-inline'>
				     <input type='radio' name='app' id='r4' value='php'>Php
				 </label>
				 <label class='checkbox-inline'>
				     <input type='radio' name='app' id='r5' value='redis'>Redis
				 </label>
				 <label class='checkbox-inline' style='margin-left:135px;margin-top:30px'>
				     <input type='radio' name='app' id='r5' value='memcached'>Memcached
				 </label>
				 <label class='checkbox-inline' style='margin-top:30px'>
				     <input type='radio' name='app' id='r5' value='tomcat'>Tomcat
				 </label>
				 <label class='checkbox-inline' style='margin-top:30px'>
				     <input type='radio' name='app' id='r5' value='system'>Init System
				 </label>
			     </div>
			     <div class='input-group' style='margin:auto;width:400px'>
			     <button class='btn btn-outline btn-danger' type='submit' value='deploy' id='d' style='width:400px;margin-top:100px'> Deploy </button>
			     <span id='r' style='display:none;width:200px;margin-top:500px'><img style='width:200px;height:200px;' src={%static 'img/wait.gif'%} />正在部署.......</span>
			     </div>
                             <script type='text/javascript'>
				 function validation(){
				    var target=document.getElementById('target');
				    if (target.value==null || target.value.replace(/(^\s*)|(\s*$)/g, "")=='')
				    {
				            alert('请输入目标主机!!!');
					    return false;
				    }
				    document.getElementById('d').style.display="none";
				    document.getElementById('r').style.display='';
				    return true;
				 }
			     </script>
			     </form>
			 </div>
		     </div>
		    </div>
	  	</div>
	    </div>
	</div>
{%if log %}
<div class='row'>
<div class='panel'> 
<div class='panel-body'>
<div class='panel panel-info' style='width:700px;height:1200px;margin:auto;'>
<div class='alert alert-info'>
<textarea style='width:100%;height:1000px;background: #300a24'>
部署日志:
{{log}}
</textarea>
</div>
</div>
</div>
</div>
</div>
{%endif%}
{%endblock%}

OpsSystem/templates/salt_hosts.html
{%extends 'base.html' %}
{%load static %}
{%block head%}
<li>
   <i class='fa fa-dashboard'></i><a href={%url 'index' %}>&nbsp Dashboard</a>
</li>
<li>
   <i class='fa fa-table'></i>&nbsp SaltStack
</li>
<li  class='active'>
<i class='fa fa-building-o'></i>&nbsp; Minions信息
</li>
{%endblock%}

{%block page_content%}

<div class='row'>
    <div class='panel panel-info'>
     <div class='panel-heading'>
	 <h3 class='panel-title'><i class='fa fa-bell'></i>&nbsp 主机信息<h3>
     </div>
     <div class='panel-body'>
          <div class='panel panel-info' style='width:auto;height:450px;margin:auto'>
	      <div class='table-responsive'>
		  <table class="table table-striped table-bordered">
		      <thead>
			  <tr class='info'>
			      <th>主机名</th>
			      <th>IP地址</th>
			      <th>CPU信息</th>
			      <th>内存信息</th>
			      <th>所属组</th>
			      <th>系统版本</th>
			      <th>主机区域</th>
			      <th>用途</th>
			  </tr>
		      </thead>
		      <tbody>
		      {%for host in hosts%}
		      <tr>
			  <td>{{host.hostname }}</td>
			  <td>{{host.ipaddress }}</td>
			  <td>{{host.cpuinfo }}</td>
			  <td>{{host.meminfo }}</td>
			  <td>{{host.group }}</td>
			  <td>{{host.osinfo }}</td>
			  <td>{{host.area }}</td>
			  <td>{{host.usage }}</td>
                       </tr>
	            {%endfor%}
		      </tbody>
		  </table>
	  </div>
      </div>
  </div>
      <div class='pager' style='argin-top:30px;width:auto;margin-left:50px'>
	  <span class='step-links'>
	      {%if hosts.has_previous %}
	      <li>  <a href="?page={{hosts.previous_page_number}}">&larr;Previous</a></li>
	      {%endif%}
	      <span class='current'>Page {{hosts.number}} of {{hosts.paginator.num_pages}}  &nbsp;&nbsp; total: {{total}} </span>
	      {%if hosts.has_next%}
	      <li> <a href="?page={{hosts.next_page_number}}">Next &rarr;</a></li>
	      {%endif%}
	  </span>
      </div>
    </div>
    <div style='text-align:center'>
	<a class='btn btn-primary' id='a' onclick='return validation();' style='width:60px;height:30px' href={%url 'salts:refresh_host_info'%}>刷新</a> 
	<span id='b' style='display:none;width:60px;height:30px'>正在刷新.....</span>
	<script type='text/javascript'>
	    function getId(id) {
		return document.getElementById(id);
	    }
            function validation() {
	    getId("a").style.display="none";
	    getId('b').style.display="";
	    return true;
	    }
        </script>
     </div>
</div>
{%endblock%}